name = "GeoGreensFunctions"
uuid = "1bc39cc2-b9cd-470c-972b-2e3fb46182c5"
authors = ["shipengcheng1230 <shipengcheng1230@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.4"
